version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - cluster.name="elastic_stack_logging"
      - node.name="elastic_stack_logging_data"
      - discovery.zen.minimum_master_nodes=1
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes: 
      - elk_data:/usr/share/elasticsearch/data      
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5     
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    environment:
      - server.name=kibana
      - server.host="0"
      - elasticsearch.url=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - logstash
    ports:
      - "5603:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:5601/ || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5     
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.0
    volumes:
      - ./logstash/logstash.conf:/config/product.logstash.conf      
    command: logstash -f /config/product.logstash.conf  
    ports:
      - "5009:5009"
    depends_on:
      - elasticsearch
    networks:
      - elk_network 

volumes:
  elk_data:

networks:
  elk_network:
